name: InvisibilityPotionVanish
version: '${version}'
main: me.wega.invisibilitypotionvanish.InvisibilityPotionVanish
api-version: "1.8"
author: ThomasWega
description: "${description}"
depend:
  - ProtocolLib